### ISSUE TITLE
Please ensure a maximum timeout is agreed upon that should be used when probing links

### ISSUE THREAD

**Issue by aquaglia** [inspire-eu-validation/ats-download-directaccess-wfs#1]

**Comment by aquaglia** [comment]
Why was this issue closed without a comment?

**Comment by ilkkarinne** [comment]
Sorry @aquaglia, my opinion is that this should not be defined at the ATS level. As far as I'm aware, there are no requirements in the referenced TG documents for the retrieval accesibility of the referred documents, thus there can be no tests imposing this kind of limits for that eiher.

At the ETS level there should be clear agreements on what is interpreted as "accessible" or "resolvable" URL, including the facts that HTTP should be used, as well as Internet DNS, and the response headers should be returned within the given time.

**Comment by aquaglia** [comment]
@ilkkarinne I think that it is important to define the existence of a finite timeout exactly at the ATS level in order to ensure testability of the ETS, where the actual values can be defined.
I am not sure I understand: the requirements in the TG DLS are actually in (8.2.1 Implementation requirements mandated by the Implementing Rule)

**Comment by ilkkarinne** [comment]
Good point @aquaglia, as there is a separate Conformance class the QoS in TG DLS, we need to create another ATS for that.

**Comment by cportele** [comment]
covered as part of the cross-cutting issues
