### ISSUE TITLE
Maybe a test for requirement 52 / 61 could be adde...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-download-directaccess-wfs#10]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Maybe a test for requirement 52 / 61 could be added by testing that for each feature type there is exactly one //wfs:FeatureType/wfs:MetadataURL and all values must be identical.
However, the TG does not seem to require this, so this would require a TG update first.
# Proposed Change
##

**Comment by thijsbrentjens** [comment]
Agreed. See [https://github.com/inspire-eu-validation/ats-download-predefined-wfs/issues/30](https://github.com/inspire-eu-validation/ats-download-predefined-wfs/issues/30)
