### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-download-directaccess-wfs#11]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

A typo: the section TG Requirement Coverage contains (in the first line) a link to [TG VS] which should refer to [TG DL].
# Proposed Change

Change link to TG DL

**Comment by cportele** [comment]
Proposed resolution:
- Implement proposed change.

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
